### ISSUE TITLE
Contributors layout does not behave correctly

### ISSUE THREAD

**Issue by jdrese** [mgear-dev/mgear-dev.github.io#1]
Contributors layout does not behave nicely with more than 3 items added into the div.

**Comment by miquelcampos** [comment]
Hi!
Here is the screen capture with a 4th contributor enabled:
![image](https://user-images.githubusercontent.com/1050212/41141147-d07821b0-6b2b-11e8-8f26-565fd8d975d1.png)

**Comment by jdrese** [comment]
Yes I fixed it but I need you to give me repository access to push the fix.

**Comment by miquelcampos** [comment]
I just granted the access to all members

**Comment by jdrese** [comment]
I've pushed the fix. But for now you have 6 members with 2 times each one of us...

**Comment by miquelcampos** [comment]
oh I see. I think the html should not be changed only the Css. 
The html is generated with Hugo framework using a toml configuration

I will check this. Thanks!

**Comment by miquelcampos** [comment]
OK the just tested the change on the CSS and works perfect!  I will update the fork and the web . Thanks again! :)
